services:
  - type: web
    name: solid-bomber-pro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 2 --worker-class gthread --max-requests 100 --max-requests-jitter 10
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: APP_PASSWORD
        value: admin
      - key: MAX_CONCURRENT_ATTACKS
        value: 10
      - key: SESSION_SECRET
        generateValue: true
