services:
  - type: web
    name: nine-11-dispatcher
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app --max-requests 500
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: APP_PASSWORD
        value: admin
      - key: MAX_CONCURRENT_ATTACKS
        value: 10
      - key: SESSION_SECRET
        generateValue: true
